version: '3'
services:
    test-redis-server:
        image: 'redis'
    node-app:
        # restart: "no"
        # restart: always
        # restart: on-failure
        restart: unless-stopped
        build: .
        ports:
            - "5001:8081"